class i4{constructor(e,t){this.data=t,this.root.name="night-road-lighting",e.add(this.root);const n=new ct({color:"#64766c",roughness:.85}),s=new ci({color:"#ffe0a1"});for(const c of[n,s])c.transparent=!0,c.onBeforeCompile=h=>{h.uniforms.uFocus=this.near,h.uniforms.uRange=this.range,h.uniforms.uZoom=this.zoom,h.vertexShader=h.vertexShader.replace("#include <common>",`#include <common>
varying vec3 vLampWorld;`).replace("#include <project_vertex>",`#include <project_vertex>
vLampWorld=(modelMatrix*instanceMatrix*vec4(position,1.)).xyz;`),h.fragmentShader=h.fragmentShader.replace("#include <common>",`#include <common>
uniform vec3 uFocus; uniform float uRange;uniform float uZoom; varying vec3 vLampWorld;`).replace("#include <opaque_fragment>",`diffuseColor.a *= uZoom*(1.-smoothstep(uRange*.65,uRange,length(vLampWorld.xz-uFocus.xz)));
#include <opaque_fragment>`)};const a=pr([new qt(.004,.078,.004).translate(0,.039,0),new qt(.033,.003,.004).translate(.015,.078,0)]);this.poles=new Dn(a,n,768),this.heads=new Dn(new qt(.013,.003,.007).translate(.032,.077,0),s,768);const r=new nn({transparent:!0,depthWrite:!1,depthTest:!0,polygonOffset:!0,polygonOffsetFactor:-1,polygonOffsetUnits:-1,uniforms:{uLevel:{value:0},uFocus:this.near},vertexShader:"varying vec2 vUv;varying vec3 vWorld;void main(){vUv=uv;vec4 world=modelMatrix*instanceMatrix*vec4(position,1.);vWorld=world.xyz;gl_Position=projectionMatrix*viewMatrix*world;}",fragmentShader:`uniform float uLevel;uniform vec3 uFocus;varying vec2 vUv;varying vec3 vWorld;void main(){vec2 p=(vUv-.5)*2.;float a=pow(max(0.,1.-dot(p,p)),2.)*.24*uLevel*(1.-smoothstep(7.,15.,length(vWorld.xz-uFocus.xz)));gl_FragColor=vec4(1.,.78,.4,a);
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`});this.pools=new Dn(new Ii(1,1).rotateX(-Math.PI/2),r,768);for(const c of[this.poles,this.heads,this.pools])c.count=0,c.frustumCulled=!1,c.instanceMatrix.setUsage(y1),this.root.add(c);const o=new gt;o.setAttribute("position",new Je(t.lamps.flatMap(c=>[c[0]+Math.cos(c[3])*.032,c[1]+.077,c[2]-Math.sin(c[3])*.032]),3)),o.setAttribute("group",new Je(t.lamps.map(c=>c[11]),1));const l=new nn({transparent:!0,depthWrite:!1,depthTest:!0,uniforms:this.uniforms,vertexShader:"uniform float uDpr;uniform float uNight;uniform float uLow;attribute float group;varying float vAlpha;void main(){vec4 p=modelViewMatrix*vec4(position,1.);float farFade=1.-smoothstep(200.,800.,-p.z);vAlpha=smoothstep(group*.012,.85+group*.012,uNight)*farFade*(.58+group*.025);if(uLow>.5&&mod(group,2.)>.5)vAlpha*=.18;gl_PointSize=clamp(18./max(1.,-p.z),1.7,3.5)*uDpr;gl_Position=projectionMatrix*p;}",fragmentShader:`varying float vAlpha;void main(){float d=length(gl_PointCoord-.5)*2.;float a=(1.-smoothstep(.2,1.,d))*vAlpha;gl_FragColor=vec4(1.,.78,.43,a);
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`});this.points=new tl(o,l),this.root.add(this.points)}data;root=new Xe;enabled=!0;poles;heads;pools;points;uniforms={uNight:{value:0},uDpr:{value:1},uLow:{value:0}};near={value:new R};level=0;range={value:17};zoom={value:1};elapsed=1;lastLow=!1;dummy=new Rt;selected=[];update(e,t,n,s,a,r){if(this.root.visible=this.enabled,this.level+=(mr(t).roads-this.level)*(1-Math.exp(-Math.min(2,e)*3)),this.zoom.value=1-Lt.smoothstep(s,18,28),this.uniforms.uNight.value=this.level,this.uniforms.uDpr.value=r,this.uniforms.uLow.value=a?1:0,this.points.visible=this.level>.001,this.heads.visible=!0,this.pools.visible=this.level>.001&&!a,this.pools.material.uniforms.uLevel.value=this.level,this.heads.material.color.set("#8e9c90").lerp(new Ye("#ffe0a1"),this.level),this.near.value.copy(n),this.elapsed+=e,this.elapsed<.18&&this.lastLow===a)return;this.elapsed=0,this.lastLow=a;const o=a?192:768;this.selected=s<28?this.data.lamps.map((c,h)=>({i:h,d:(c[0]-n.x)**2+(c[2]-n.z)**2})).filter(c=>c.d<17**2).sort((c,h)=>c.d-h.d||c.i-h.i).slice(0,o).map(c=>c.i):[];const l=this.selected.at(-1);this.range.value=l===void 0?17:Math.min(17,Math.hypot(this.data.lamps[l][0]-n.x,this.data.lamps[l][2]-n.z));for(let c=0;c<this.selected.length;c++){const h=this.data.lamps[this.selected[c]];this.dummy.position.set(h[0],h[1],h[2]),this.dummy.rotation.set(0,h[3],0),this.dummy.scale.set(1,1,1),this.dummy.updateMatrix(),this.poles.setMatrixAt(c,this.dummy.matrix),this.heads.setMatrixAt(c,this.dummy.matrix),this.dummy.position.set(h[4],h[5],h[6]),this.dummy.rotation.order="YXZ",this.dummy.rotation.set(h[10],h[9],0),this.dummy.scale.set(h[7],1,h[8]),this.dummy.updateMatrix(),this.pools.setMatrixAt(c,this.dummy.matrix)}for(const c of[this.poles,this.heads,this.pools])c.count=this.selected.length,c.instanceMatrix.needsUpdate=!0}metrics(){return{enabled:this.enabled,lamps:this.data.lamps.length,roads:this.data.roadIds.length,near:this.selected.length,pools:this.pools.visible?this.pools.count:0,level:this.level}}}function js(i,e,t,n,s,a,r,o=!1){const l=new Xe;l.position.set(e,t,n),l.name="place-light",l.userData.illumination=!0,i.add(l);const c=new ci({color:"#ffdd99"}),h=new wt(new qt(Math.min(s*.65,.022),.002,.005),c);h.position.y=r,l.add(h);const d=new nn({transparent:!0,depthTest:!0,depthWrite:!1,polygonOffset:!0,polygonOffsetFactor:-1,polygonOffsetUnits:-1,uniforms:{uLevel:{value:0}},vertexShader:"varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}",fragmentShader:`varying vec2 vUv;uniform float uLevel;void main(){vec2 p=(vUv-.5)*2.;float a=pow(max(0.,1.-dot(p,p)),1.5)*.28*uLevel;gl_FragColor=vec4(1.,.77,.38,a);
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`}),u=new wt(new Ii(s,a).rotateX(-Math.PI/2),d);u.position.y=.001,u.userData.localPool=!0,l.add(u),h.userData.localLight=!0,h.userData.decorative=o;let f=0,y=performance.now();return{root:l,update(x,p=!1){const m=mr(x),b=o?m.decorative:m.places,_=performance.now();f+=(b-f)*(1-Math.exp(-Math.min(2,(_-y)/1e3)*3)),y=_;const g=f;h.visible=g>.001,u.visible=g>.001&&!p,c.color.set("#ffdd99").multiplyScalar(.25+.75*g),d.uniforms.uLevel.value=g}}}