#!/usr/bin/env node
/**
 * verify-fresh.mjs — is what is on disk what the generators would produce now?
 *
 * Every generator in this pipeline has a --check mode EXCEPT the bundler step,
 * and that gap is invisible: a stale dist/ serves happily and every downstream
 * gate passes against it, because the gates check dist against the mirror, not
 * dist against src.
 *
 * ⛔ A timestamp is not the judge. Measured: dist/site.js was a day older than
 * src/, which looked like staleness and was not — the regenerated bytes were
 * identical, because the src change (deleting a file nothing imported) could not
 * reach the bundle. The inference from mtime was wrong in the harmless
 * direction; the same inference is available to be wrong in the other one.
 *
 * ⭐ So regenerate and compare BYTES. That is the same discipline
 * slice-modules --check and build-site --check already apply; this closes the
 * one step that lacked it.
 *
 *   node scripts/verify-fresh.mjs [--entry src/index.js] [--dist dist/site.js] [--served site/_next/static/chunks/site.port.js] [--esbuild node_modules/.bin/esbuild]
 *
 * 中文规格（自 scripts/README.md 迁入，v0.3.21；本表另一拼写：`verify-fresh.mjs`）
 * **新鲜度门**：`src/` → `dist/` → `site/` 是否同步。⛔ 链条上**只要有一步缺 `--check`，整条链的绿灯就可能过期**——过期的产物照样伺服，下游门照样全绿（它们比的是产物对镜像，不是产物对源码）。⛔ **时间戳不是判据**：实测一次 mtime 显示过期而重建字节完全相同。⚠ 必须同时查「产物是不是源码现在构建出来的」与「伺服的是不是那一份」——只查前者，缺口只是往下游挪一步
 * **生成物新鲜度门**：盘上的构建产物是否等于生成器**现在**会产出的东西。管线里每个生成器都有 `--check`，唯独打包一步没有——陈旧的 dist/ 照常伺服、下游门全绿，这道门补上那个洞
 * `node verify-fresh.mjs`
 */
import { readFile, mkdtemp, rm } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { cli } from "./lib/cli.mjs";
import { sha256 } from "./lib/hash.mjs";

cli({ known: ["entry", "dist", "served", "esbuild"], bools: [], file: import.meta.url });

// ⛔ NOT hardcoded. These three paths named one project's shape for several
// releases, which is how a gate ends up FATAL on a port that is merely built
// differently. A whole-site port has NO bundle step at all: it ships the
// packer's own chunks verbatim, and this gate's whole subject is absent.
const args = process.argv.slice(2);
const flag = (n, d) => { const i = args.indexOf("--" + n); return i >= 0 && args[i + 1] !== undefined ? args[i + 1] : d; };
const ENTRY = path.resolve(flag("entry", "src/index.js"));
const DIST = path.resolve(flag("dist", "dist/site.js"));
const SERVED = path.resolve(flag("served", "site/_next/static/chunks/site.port.js"));

let fail = 0;
console.log("=== verify-fresh ===");

// ⭐ A gate that examined nothing must SAY it examined nothing. Exiting 0 in
// silence and exiting 0 after checking everything look identical from the
// outside, and only one of them means anything.
if (!existsSync(ENTRY)) {
  console.log(`  note — ${path.relative(process.cwd(), ENTRY)} does not exist, so this port has no bundle step`);
  console.log(`         and nothing for this gate to regenerate. The equivalent coverage for a`);
  console.log(`         verbatim-chunk port is slice-modules --check plus build-site --check.`);
  console.log(`\nSKIPPED — no bundle step in this port. Pass --entry to point at one.`);
  process.exit(0);
}

const tmp = await mkdtemp(path.join(tmpdir(), "fresh-"));
const rebuilt = path.join(tmp, path.basename(DIST));
// ⛔ THE PROJECT'S OWN esbuild, never a fetched one. This gate asks "is dist/ what
// the generator would produce NOW" — and the generator is the esbuild the project
// pinned in its devDependencies (make-standalone writes it). A bare `npx esbuild`
// fell back to fetching the newest release when no local install existed, and a
// global pin (tried: 0.28.2) is the same mistake in the other direction: either
// way the rebuild uses a different bundler than dist/ and a byte drift reads as
// staleness. Resolve the local binary (or --esbuild <path>); if there is none,
// say so and stop — a gate that quietly picks its own tool is not a gate.
const ESBUILD = flag("esbuild", path.join(process.cwd(), "node_modules", ".bin", "esbuild"));
if (!existsSync(ESBUILD)) {
  console.error(`FATAL: no esbuild at ${ESBUILD}`);
  console.error("       verify-fresh rebuilds with the PROJECT's pinned esbuild (devDependencies); install it, or pass --esbuild <path>.");
  process.exit(2);
}
const r = spawnSync(ESBUILD, [ENTRY, "--bundle", "--format=iife", `--outfile=${rebuilt}`], { encoding: "utf8" });
if (r.status !== 0) {
  console.error(`FATAL — rebuilding ${path.relative(process.cwd(), ENTRY)} failed:\n${(r.stderr || "").split("\n").slice(0, 12).join("\n")}`);
  process.exit(5);
}

const now = await readFile(rebuilt);
const disk = await readFile(DIST).catch(() => null);
if (!disk) { fail++; console.log(`  FAIL dist/site.js is missing — run \`npm run src:build\``); }
else if (sha256(now) !== sha256(disk)) {
  fail++;
  console.log(`  FAIL dist/site.js differs from a fresh build of src/`);
  console.log(`         on disk ${sha256(disk).slice(0, 16)}   rebuilt ${sha256(now).slice(0, 16)}`);
  console.log(`       src/ changed after the bundle was built. Run \`npm run src:build && npm run build\`.`);
} else console.log(`  ok   dist/site.js is a current build of src/  (${sha256(disk).slice(0, 16)})`);

// ⚠ And the served copy must be that same bundle. build-site copies it in, so a
// build-site that was never re-run leaves the OLD bundle being served while
// dist/ is correct — the gap moves one step downstream rather than closing.
const served = await readFile(SERVED).catch(() => null);
if (!served) { fail++; console.log(`  FAIL site/ does not carry the port bundle — run \`npm run build\``); }
else if (disk && sha256(served) !== sha256(disk)) {
  fail++;
  console.log(`  FAIL the bundle in site/ is not the one in dist/`);
  console.log(`         dist ${sha256(disk).slice(0, 16)}   served ${sha256(served).slice(0, 16)}`);
  console.log(`       Run \`npm run build\` — the shell build copies dist/ into site/.`);
} else console.log(`  ok   site/ serves exactly the bundle in dist/`);

await rm(tmp, { recursive: true, force: true });
console.log(fail ? `\nFAIL — ${fail} staleness problem(s).` : `\nPASS — src/ -> dist/ -> site/ are in step.`);
process.exit(fail ? 1 : 0);
